name: UPM
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'upm'

jobs:
  deploy-upm:
    name: Deploy to UPM branch
    runs-on: ubuntu-latest

    env:
      PKG_ROOT: Packages/com.chark.scriptable-scenes

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout
      run: |
        git branch -d ${{ github.event.inputs.branch }} &> /dev/null || echo the branch not found
        git subtree split -P "$PKG_ROOT" -b ${{ github.event.inputs.branch }}
        git checkout ${{ github.event.inputs.branch }}

    - name: Rename Samples to Samples~
      run: |
        mv "$PKG_ROOT/Samples" "$PKG_ROOT/Samples~"

    - name: Push
      run: |
        git push -f -u origin ${{ github.event.inputs.branch }}
